---
abstract: 'Generate Tickets (Signed HTTP Cookies) for mod_auth_pubtkt protected websites.'
author:
  - 'Assaf Gordon <gordon@cshl.edu>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Authen-ModAuthPubTkt
no_index:
  directory:
    - t
    - inc
requires:
  File::Temp: 0
  IPC::Run3: 0
  MIME::Base64: 0
  Test::More: 0
version: v0.1.1
